services:
  game-server:
    container_name: space-shooting
    build: .
    ports:
      - 8325:3000
    environment:
      - HOST_PORT=8325
    volumes:
      - ./:/app
      - /app/server/node_modules
    working_dir: /app
    command: node server/server.js
